### ISSUE TITLE
error: use of undeclared identifier 'napi_object_freeze'

### ISSUE THREAD

**Issue by bconnorwhite** [ApsarasX/llvm-bindings#6]
I noticed a bunch of "use of undeclared identifier" errors after upgrading to v0.2.0 coming from `node-addon-api` on postinstall (with node v15), downgrading to node v14 fixes the issue

**Comment by bconnorwhite** [comment]
Looks like it must be the bump from node-addon-api 3.1.0 -> 3.2.0

**Comment by ApsarasX** [comment]
Can you provide some sample code that causes this error?

**Comment by bconnorwhite** [comment]
This was when I ran postinstall

**Comment by ApsarasX** [comment]
Yes, this problem is indeed caused by compatibility. The compatible version of napi_object_freeze is as follows
![image](https://user-images.githubusercontent.com/24390069/119435985-e1998c00-bd4d-11eb-940d-6fef3d69c3f3.png)

![image](https://user-images.githubusercontent.com/24390069/119435952-cfb7e900-bd4d-11eb-99c9-f3519971a4c2.png)
